export const WEBSITES = {
  "komikdewasa.mom": {
    domain: "komikdewasa.mom",
    default: "https://komikdewasa.mom",
    search: "https://komikdewasa.mom/?s=",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".infotable tr:nth-of-type(2) > td:nth-of-type(2)",
      type: ".infotable tr:nth-of-type(3) > td:nth-of-type(2)",
      author: ".infotable .author i",
      genre: ".seriestugenre a",
      description: "entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".eph-num",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  mahnwadesu: {
    domain: "baca03.manhwadesu.co.in",
    default: "https://baca03.manhwadesu.co.in",
    search: "https://baca03.manhwadesu.co.in/?s=",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  lianscans: {
    domain: "lianscans.com",
    default: "https://www.lianscans.com",
    search: "https://www.lianscans.com/?s=",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(3) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea",
      },
    },
  },

  "komikdewasa.art": {
    domain: "komikdewasa.art",
    default: "https://komikdewasa.art",
    search: "https://komikdewasa.art/?s=",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a.series",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".infotable tr:nth-child(2) td:nth-child(2)",
      type: ".infotable tr:nth-child(2) td:nth-child(2)",
      author: ".infotable .author i",
      genre: ".seriestugenre a",
      description: "entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".eph-num",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  sekaikomik: {
    domain: "www.sekaikomik.lat",
    default: "https://www.sekaikomik.lat",
    search: "https://www.sekaikomik.lat/?s=",
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: ".bsx a:nth-of-type(2)",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  sxkomik: {
    domain: "www.sxkomik.art",
    default: "https://www.sxkomik.art/",
    search: "https://www.sxkomik.art/search?q=",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".pt-2",
        text: ".text-sm",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".pt-2",
        text: ".text-sm",
        link: "a",
      },
      title: "h1.text-2xl",
      cover: ".rounded-b-md img",
      status: ".bg-base-100 .flex:nth-child(1) span:nth-child(2)",
      type: ".bg-base-100 .flex:nth-child(2) span:nth-child(2)",
      author: ".bg-base-100 .flex:nth-child(2) span:nth-child(2)",
      genre: ".flex a",
      description: ".Sinopsis p",
      chapter: {
        parent: ".flex",
        text: "#text",
        link: "a",
        image: ".max-w-4xl img",
      },
    },
  },

  manhwadesu: {
    domain: "manhwadesu.ws",
    default: "https://manhwadesu.ws/",
    search: "https://manhwadesu.ws/?s=",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  "baca03.manhwadesu": {
    domain: "baca03.manhwadesu.co.in",
    default: "https://baca03.manhwadesu.co.in",
    search: "https://baca03.manhwadesu.co.in/?s=",
    isTsRead: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  "mangasusu.sbs": {
    domain: "mangasusu.sbs",
    default: "https://mangasusu.sbs",
    search: "https://mangasusu.sbs/?s=",
    isTsRead: true,
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(3) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  "komik5.mangatoon.cc": {
    domain: "komik5.mangatoon.cc",
    default: "https://komik5.mangatoon.cc",
    search: "https://komik5.mangatoon.cc/?s=",
    // comicDelay: 8000,
    // chapterDelay: 4000,
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(3) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },
  "shinigami07.com": {
    domain: "shinigami07.com",
    default: "https://shinigami07.com",
    search: "https://shinigami07.com/?post_type=wp-manga&s=",
    comicDelay: 8000,
    chapterDelay: 4000,
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".post-title",
        text: "h3",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".latest .col-6.col-sm-6.col-md-6.col-xl-3",
        text: ".series-title",
        link: ".series-link",
      },
      title: ".post-title h1",
      cover: ".summary_image img",
      type: ".post-content .post-content_item:nth-of-type(7) > .summary-content",
      author: ".post-content .post-content_item:nth-of-type(4) > .summary-content",
      status: ".post-status .post-content_item:nth-of-type(2) > .summary-content",
      description: ".description-summary",
      genre: ".genres-content a",
      chapter: {
        parent: ".wp-manga-chapter",
        text: ".chapter-manhwa-title",
        link: ".chapter-link a",
        image: ".image-vertical img",
      },
    },
  },
  "komiku.id": {
    domain: "komiku.id",
    alternative: "komikindo.biz",
    default: "https://komiku.id/pustaka",
    search: "https://komiku.id/?post_type=manga&s=",
    elements: {
      listTitle: {
        parent: ".kan",
        text: "h3",
        link: "a",
      },
      title: ".inftable tr:nth-of-type(1) > td:nth-of-type(2)",
      cover: ".ims img",
      type: ".inftable tr:nth-of-type(3) > td:nth-of-type(2)",
      author: ".inftable tr:nth-of-type(5) > td:nth-of-type(2)",
      status: ".inftable tr:nth-of-type(6) > td:nth-of-type(2)",
      description: ".desc",
      genre: "li.genre",
      chapter: {
        parent: "td.judulseries",
        text: "a span",
        link: "a",
        image: ".ww",
      },
    },
  },
  "komiku.com": {
    domain: "komiku.com",
    alternative: "komikindo.biz",
    default: "https://komiku.com/manga/?order=update",
    search: "https://komiku.com/?s=",
    elements: {
      listTitle: {
        parent: ".bs",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      type: ".infotable tr:nth-of-type(3) > td:nth-of-type(2)",
      author: ".infotable tr:nth-of-type(5) > td:nth-of-type(2)",
      status: ".infotable tr:nth-of-type(2) > td:nth-of-type(2)",
      description: ".entry-content p",
      genre: ".seriestugenre a",
      chapter: {
        parent: ".clstyle li",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },
  "westmanga.fun": {
    domain: "westmanga.fun",
    alternative: "komikindo.biz",
    default: "https://westmanga.fun",
    search: "https://westmanga.fun/?s=",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".postbody .bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bixbox:nth-of-type(2) .bsx",
        text: ".tt a",
        link: ".tt a",
      },
      title: ".entry-title",
      cover: ".thumb img",
      type: "tr:nth-of-type(2) > td:nth-of-type(2)",
      author: "tr:nth-of-type(3) > td:nth-of-type(2)",
      status: "tr:nth-of-type(1) > td:nth-of-type(2)",
      description: ".entry-content",
      genre: ".seriestugenre a",
      chapter: {
        parent: ".chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },
  "soulscans.my.id": {
    domain: "soulscans.my.id",
    alternative: "komikindo.biz",
    default: "https://soulscans.my.id",
    search: "https://soulscans.my.id/?s=",
    isLazyLoad: true,
    elements: {
      listTitle: {
        parent: ".bixbox:nth-of-type(2) .bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1",
      cover: ".thumb img",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      status: ".imptdt:nth-of-type(1) i",
      description: ".entry-content",
      genre: ".mgen a",
      chapter: {
        parent: "#chapterlist li",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },
  "monzeekomik.my.id": {
    domain: "monzeekomik.my.id",
    alternative: "komikindo.biz",
    default: "https://monzeekomik.my.id",
    search: "https://monzeekomik.my.id/?s=",
    elements: {
      listTitle: {
        parent: ".bixbox:nth-of-type(2) .uta",
        text: "h4",
        link: "a.series",
      },
      title: "h1",
      cover: ".thumb img",
      type: ".imptdt:nth-of-type(2) a",
      // author: ".imptdt:nth-of-type(4) i",
      // status: ".imptdt:nth-of-type(1) i",
      description: ".entry-content",
      genre: ".mgen a",
      chapter: {
        parent: "#chapterlist li",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },
  "komikindo2.com": {
    domain: "komikindo2.com",
    alternative: "komiku.com",
    default: "https://komikindo2.com/komik-terbaru/",
    search: "https://komikindo2.com/?s=",
    elements: {
      listTitle: {
        parent: ".animepost",
        text: "h4",
        link: ".animposx > a",
      },
      title: ".infoanime h1",
      cover: ".thumb img",
      type: ".spe span:nth-of-type(7) > a",
      author: ".spe span:nth-of-type(3)",
      status: ".spe span:nth-of-type(2)",
      description: ".desc p",
      genre: ".genre-info a",
      chapter: {
        parent: ".listeps li",
        text: ".lchx",
        link: ".lchx a",
        image: ".chapter-image img",
      },
    },
  },
};

export const TYPES = {
  Manga: 1,
  Manhua: 2,
  Manhwa: 3,
  manga: 1,
  manhua: 2,
  manhwa: 3,
};

export const STATUSES = {
  OnGoing: 1,
  Ongoing: 1,
  ongoing: 1,
  Berjalan: 1,
  berjalan: 1,
  Hiatus: 2,
  hiatus: 2,
  Tamat: 3,
  tamat: 3,
};

export const GENRES = {
  Aksi: 1,
  Action: 1,
  aksi: 1,
  action: 1,
  "Bela Diri": 2,
  "Martial Arts": 2,
  "Martial Art": 2,
  "Bela diri": 2,
  "Martial arts": 2,
  "Martial art": 2,
  "bela Diri": 2,
  "martial Arts": 2,
  "martial Art": 2,
  "bela diri": 2,
  "martial arts": 2,
  Dewasa: 3,
  Adult: 3,
  Aldult: 3,
  dewasa: 3,
  Drama: 4,
  drama: 4,
  Ecchi: 5,
  ecchi: 5,
  Fantasi: 6,
  Fantasy: 6,
  fantasi: 6,
  Game: 7,
  game: 7,
  "Gender Bender": 8,
  "Gender bender": 8,
  "gender Bender": 8,
  "gender bender": 8,
  Harem: 9,
  harem: 9,
  Isekai: 10,
  isekai: 10,
  Komedi: 11,
  Comedy: 11,
  komedi: 11,
  cultivation: 12,
  Cultivation: 12,
  Kultivasi: 12,
  kultivasi: 12,
  Mecha: 13,
  mecha: 13,
  Metropolis: 14,
  metropolis: 14,
  Misteri: 15,
  Mystery: 15,
  misteri: 15,
  Murim: 16,
  murim: 16,
  Olahraga: 17,
  Sports: 17,
  olahraga: 17,
  Reinkarnasi: 18,
  Reincarnation: 18,
  reincarnation: 18,
  reinkarnasi: 18,
  Romantis: 19,
  Romance: 19,
  romantis: 19,
  "School Life": 20,
  "School life": 20,
  "school Life": 20,
  "school life": 20,
  Zombie: 21,
  zombie: 21,
};
