export const WEBSITES = {
  "komikdewasa.mom": {
    domain: "komikdewasa.mom",
    default: "https://komikdewasa.mom",
    search: "https://komikdewasa.mom/?s=",
    alternative: "baca03.mahnwadesu.co.in",
    isTsRead: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".infotable tr:nth-of-type(2) > td:nth-of-type(2)",
      type: ".infotable tr:nth-of-type(3) > td:nth-of-type(2)",
      author: ".infotable .author i",
      genre: ".seriestugenre a",
      description: "entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".eph-num",
        link: "a",
        image: "#readerarea",
      },
    },
  },

  "baca03.mahnwadesu.co.in": {
    domain: "baca03.manhwadesu.co.in",
    default: "https://baca03.manhwadesu.co.in",
    search: "https://baca03.manhwadesu.co.in/?s=",
    alternative: "lianscans.com",
    isTsRead: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  "lianscans.com": {
    domain: "lianscans.com",
    default: "https://www.lianscans.com",
    search: "https://www.lianscans.com/?s=",
    alternative: "sekaikomik.lat",
    isLazyLoad: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(3) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea",
      },
    },
  },

  // "komikdewasa.art": {
  //   domain: "komikdewasa.art",
  //   default: "https://komikdewasa.art",
  //   search: "https://komikdewasa.art/?s=",
  //   isTsRead: true,
  //   searchElements: {
  //     listTitle: {
  //       parent: ".bsx",
  //       text: ".tt",
  //       link: "a",
  //     },
  //   },
  //   elements: {
  //     listTitle: {
  //       parent: ".bs .bsx",
  //       text: ".tt",
  //       link: "a",
  //     },
  //     title: "h1.entry-title",
  //     cover: ".thumb img",
  //     status: ".infotable tr:nth-child(2) td:nth-child(2)",
  //     type: ".infotable tr:nth-child(2) td:nth-child(2)",
  //     author: ".infotable .author i",
  //     genre: ".seriestugenre a",
  //     description: "entry-content p",
  //     chapter: {
  //       parent: ".eplister .chbox",
  //       text: ".eph-num",
  //       link: "a",
  //       image: "#readerarea img",
  //     },
  //   },
  // },

  "sekaikomik.lat": {
    domain: "www.sekaikomik.lat",
    default: "https://www.sekaikomik.lat",
    search: "https://www.sekaikomik.lat/?s=",
    alternative: "manhwadesu.ws",
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: ".bsx a:nth-of-type(2)",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  // "sxkomik.art": {
  //   domain: "www.sxkomik.art",
  //   default: "https://www.sxkomik.art/",
  //   search: "https://www.sxkomik.art/search?q=",
  //   isLazyLoad: true,
  //   searchElements: {
  //     listTitle: {
  //       parent: ".pt-2",
  //       text: ".text-sm",
  //       link: "a",
  //     },
  //   },
  //   elements: {
  //     listTitle: {
  //       parent: ".pt-2",
  //       text: ".text-sm",
  //       link: "a",
  //     },
  //     title: "h1.text-2xl",
  //     cover: ".rounded-b-md img",
  //     status: ".bg-base-100 .flex:nth-child(1) span:nth-child(2)",
  //     type: ".bg-base-100 .flex:nth-child(2) span:nth-child(2)",
  //     author: ".bg-base-100 .flex:nth-child(2) span:nth-child(2)",
  //     genre: ".flex a",
  //     description: ".Sinopsis p",
  //     chapter: {
  //       parent: ".flex",
  //       text: "#text",
  //       link: "a",
  //       image: ".max-w-4xl img",
  //     },
  //   },
  // },

  "manhwadesu.ws": {
    domain: "manhwadesu.ws",
    default: "https://manhwadesu.ws/",
    search: "https://manhwadesu.ws/?s=",
    alternative: "baca03.manhwadesu.co.in",
    isTsRead: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea",
      },
    },
  },

  "baca03.manhwadesu.co.in": {
    domain: "baca03.manhwadesu.co.in",
    default: "https://baca03.manhwadesu.co.in",
    search: "https://baca03.manhwadesu.co.in/?s=",
    alternative: "mangasusu.sbs",
    isTsRead: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(4) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  "mangasusu.sbs": {
    domain: "mangasusu.sbs",
    default: "https://mangasusu.sbs",
    search: "https://mangasusu.sbs/?s=",
    alternative: "komik5.mangatoon.cc",
    isTsRead: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".luf",
        text: "h4",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(3) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },

  "komik5.mangatoon.cc": {
    domain: "komik5.mangatoon.cc",
    default: "https://komik5.mangatoon.cc",
    search: "https://komik5.mangatoon.cc/?s=",
    alternative: "komikdewasa.mom",
    isTsRead: true,
    searchElements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
    },
    elements: {
      listTitle: {
        parent: ".bsx",
        text: ".tt",
        link: "a",
      },
      title: "h1.entry-title",
      cover: ".thumb img",
      status: ".imptdt:nth-of-type(1) i",
      type: ".imptdt:nth-of-type(2) a",
      author: ".imptdt:nth-of-type(3) i",
      genre: ".mgen a",
      description: ".entry-content p",
      chapter: {
        parent: ".eplister .chbox",
        text: ".chapternum",
        link: "a",
        image: "#readerarea img",
      },
    },
  },
};

export const TYPES = {
  Manga: 1,
  Manhua: 2,
  Manhwa: 3,
  manga: 1,
  manhua: 2,
  manhwa: 3,
};

export const STATUSES = {
  OnGoing: 1,
  Ongoing: 1,
  ongoing: 1,
  Berjalan: 1,
  berjalan: 1,
  Hiatus: 2,
  hiatus: 2,
  Tamat: 3,
  tamat: 3,
};

export const GENRES = {
  Aksi: 1,
  Action: 1,
  aksi: 1,
  action: 1,
  "Bela Diri": 2,
  "Martial Arts": 2,
  "Martial Art": 2,
  "Bela diri": 2,
  "Martial arts": 2,
  "Martial art": 2,
  "bela Diri": 2,
  "martial Arts": 2,
  "martial Art": 2,
  "bela diri": 2,
  "martial arts": 2,
  Dewasa: 3,
  Adult: 3,
  Aldult: 3,
  dewasa: 3,
  Drama: 4,
  drama: 4,
  Ecchi: 5,
  ecchi: 5,
  Fantasi: 6,
  Fantasy: 6,
  fantasi: 6,
  Game: 7,
  game: 7,
  "Gender Bender": 8,
  "Gender bender": 8,
  "gender Bender": 8,
  "gender bender": 8,
  Harem: 9,
  harem: 9,
  Isekai: 10,
  isekai: 10,
  Komedi: 11,
  Comedy: 11,
  komedi: 11,
  cultivation: 12,
  Cultivation: 12,
  Kultivasi: 12,
  kultivasi: 12,
  Mecha: 13,
  mecha: 13,
  Metropolis: 14,
  metropolis: 14,
  Misteri: 15,
  Mystery: 15,
  misteri: 15,
  Murim: 16,
  murim: 16,
  Olahraga: 17,
  Sports: 17,
  olahraga: 17,
  Reinkarnasi: 18,
  Reincarnation: 18,
  reincarnation: 18,
  reinkarnasi: 18,
  Romantis: 19,
  Romance: 19,
  romantis: 19,
  "School Life": 20,
  "School life": 20,
  "school Life": 20,
  "school life": 20,
  Zombie: 21,
  zombie: 21,
};
